export type ContentType =
  | 'meditation'
  | 'sleep'
  | 'breathing'
  | 'sound'
  | 'music'
  | 'course'

/** Ambient audio generated by the Web Audio engine for a given session. */
export type SoundscapeId =
  | 'silence'
  | 'bowl'
  | 'rain'
  | 'ocean'
  | 'forest'
  | 'fire'
  | 'whitenoise'
  | 'brownnoise'
  | 'pinknoise'
  | 'thunder'
  | 'crickets'
  | 'chimes'
  | 'river'
  | 'cafe'
  | 'train'
  | 'space'
  | 'wind'
  | 'binaural-alpha'
  | 'binaural-delta'
  | 'binaural-theta'
  | 'piano'
  | 'strings'
  | 'lofi'
  | 'morning'

export type GradientKey =
  | 'dusk'
  | 'ocean'
  | 'forest'
  | 'ember'
  | 'lavender'
  | 'midnight'
  | 'dawn'
  | 'rose'
  | 'gold'
  | 'slate'
  | 'sky'

export interface Session {
  id: string
  type: ContentType
  title: string
  subtitle?: string
  category: string
  narrator: string
  description: string
  durationMin: number
  level: 'Beginner' | 'Intermediate' | 'All Levels'
  tags: string[]
  soundscape: SoundscapeId
  gradient: GradientKey
}

export interface BreathingPattern {
  id: string
  title: string
  description: string
  benefit: string
  inhale: number
  holdIn: number
  exhale: number
  holdOut: number
  cycles: number
  gradient: GradientKey
}

export interface Course {
  id: string
  title: string
  description: string
  category: string
  gradient: GradientKey
  sessionIds: string[]
}

export interface AffirmationCard {
  id: string
  category: string
  text: string
}
